
ball:
  x:
    $class: "osdt_example_lib.models.bouncing_ball.State"
    y_position: 2.0
    y_velocity: 1.0
  p:
    $class: "osdt_example_lib.models.bouncing_ball.Params"
    gravity: 9.81
    restitution: .95
  id: "ball"
  c: "osdt_example_lib.models.bouncing_ball.C"
  f: "osdt_example_lib.models.bouncing_ball.F"
  d: "osdt_example_lib.models.bouncing_ball.D"
  g: "osdt_example_lib.models.bouncing_ball.G"
  u: "osdt_example_lib.models.bouncing_ball.U"
  y: "osdt_example_lib.models.bouncing_ball.Y_dict"


config:
  time: 19.0
  jumps: 300


