data_file: null

ball:
  id: "ball"
  c: "osdt_example_lib.models.bouncing_ball.C"
  f: "osdt_example_lib.models.bouncing_ball.F"
  d: "osdt_example_lib.models.bouncing_ball.D"
  g: "osdt_example_lib.models.bouncing_ball.G"
  u: "osdt_example_lib.models.bouncing_ball.U"
  y: "osdt_example_lib.models.bouncing_ball.Y_dict"
  x_vals:
    y_position: 12.0
    y_velocity: 1.0
  p_vals:
    gravity: 9.81
    restitution: .95

config:
  time: 9.0
  jumps: 300

run: 
  actions: [
    ["osdt_example_lib.models.bouncing_ball.create", "data_file:ball"],
    ["osdt.edit_config", "data_file:config"],
    ["osdt.run",{}],
    ["osdt_example_lib.functions.script_bouncing_ball.figure1",{}],
    ["osdt.display",{}]
  ]