ball:
  id: "ball"
  c: "osdt_example_lib.models.bouncing_ball.C"
  f: "osdt_example_lib.models.bouncing_ball.F"
  d: "osdt_example_lib.models.bouncing_ball.D"
  g: "osdt_example_lib.models.bouncing_ball.G"
  u: "osdt_example_lib.models.bouncing_ball.U"
  y: "osdt_example_lib.models.bouncing_ball.Y_dict"
  x_vals:
    y_position: 12.0
    y_velocity: 1.0
  p_vals:
    gravity: 9.81
    restitution: .95

pos_sh:
  id: "pos_sampler"
  c: "osdt_example_lib.models.sample_hold_sensor.C"
  f: "osdt_example_lib.models.sample_hold_sensor.F"
  d: "osdt_example_lib.models.sample_hold_sensor.D"
  g: "osdt_example_lib.models.sample_hold_sensor.G"
  u: "osdt_example_lib.models.sample_hold_sensor.U"
  y: "osdt_example_lib.models.sample_hold_sensor.Y"
  x_vals:
    value: 0.0
    timer: 0.0
  p_vals:
    sample_period: 0.1
    sample_field: "y_position"

vel_sh:
  id: "vel_sampler"
  c: "osdt_example_lib.models.sample_hold_sensor.C"
  f: "osdt_example_lib.models.sample_hold_sensor.F"
  d: "osdt_example_lib.models.sample_hold_sensor.D"
  g: "osdt_example_lib.models.sample_hold_sensor.G"
  u: "osdt_example_lib.models.sample_hold_sensor.U"
  y: "osdt_example_lib.models.sample_hold_sensor.Y"
  x_vals:
    value: 0.0
    timer: 0.0
  p_vals:
    sample_period: 0.1
    sample_field: "y_velocity"

config:
  time: 9.0
  jumps: 300

env_load:
  path: "output/bb_sh"

env_save:
  path: "output/bb_sh"
  overwrite: True

figure1:
  pos_sensor: "pos_sampler"
  vel_sensor: "vel_sampler"


connections:
  matrix: [
    ["pos_sampler","ball","osdt_example_lib.models.sample_hold_sensor.INPUT"],
    ["vel_sampler","ball","osdt_example_lib.models.sample_hold_sensor.INPUT"],
    ["ball","pos_sampler","'test'"]
  ]
  get_systems: true

#"create_pos_sh","create_vel_sh","connect_pos_sh","connect_vel_sh","edit_config","run_env","create_plot","display","save_env"]
data_file: null

create_ball: ["osdt_example_lib.models.sample_hold_sensor.create","data_file:ball"]
create_samplers: ["osdt_example_lib.models.sample_hold_sensor.create", "data_file:pos_sh","data_file:vel_sh"]
edit_config: ["osdt.edit_config", "data_file:config2" , "data_file:config3"]
load_env: ["osdt.load_env","env_load"]
display: ["osdt.display"]
run:  ["osdt_example_lib.functions.script_bouncing_ball.main"]
create_plot: ["osdt_example_lib.functions.bouncing_ball_sample_hold.figure1", "data_file:figure1"]


script2:
  actions: [
    "load_env",
    "create_plot",
    "display"
  ]

script1: 
  arguments:
    data_file: null
  actions: [
    ["osdt_example_lib.models.bouncing_ball.create", "data_file:ball"],
    ["osdt_example_lib.models.sample_hold_sensor.create", "data_file:pos_sh","data_file:vel_sh"],
    ["osdt.connect_components","data_file:connections"],
    ["osdt.edit_config", "data_file:config"],
    ["osdt.run"],
    ["osdt.save_env","data_file:env_save"],
    ["osdt_example_lib.functions.bouncing_ball.ball_sampled_figure", "data_file:figure1"],
    ["osdt.display"]
]