ball:
  x:
    $class: "osdt_example.models.bouncing_ball.State"
    y_position: 2.0
    y_velocity: 1.0
  p:
    $class: "osdt_example.models.bouncing_ball.Params"
    gravity: 9.81
    restitution: .95
  c: "osdt_example.models.bouncing_ball.C"
  f: "osdt_example.models.bouncing_ball.F"
  d: "osdt_example.models.bouncing_ball.D"
  g: "osdt_example.models.bouncing_ball.G"
  u: "osdt_example.models.bouncing_ball.U"
  y: "osdt_example.models.bouncing_ball.Y_dict"
  id: "ball"

pos_sh:
  x:
    $class: "osdt_example.models.sample_hold_sensor.State"
    value: 0.0
    timer: 0.0
  p:
    $class: "osdt_example.models.sample_hold_sensor.Params"
    sample_period: 0.1
    sample_field: "y_position"
  c: "osdt_example.models.sample_hold_sensor.C"
  f: "osdt_example.models.sample_hold_sensor.F"
  d: "osdt_example.models.sample_hold_sensor.D"
  g: "osdt_example.models.sample_hold_sensor.G"
  u: "osdt_example.models.sample_hold_sensor.U"
  y: "osdt_example.models.sample_hold_sensor.Y"
  id: "pos_sampler"

vel_sh:
  x:
    $class: "osdt_example.models.sample_hold_sensor.State"
    value: 0.0
    timer: 0.0
  p:
    $class: "osdt_example.models.sample_hold_sensor.Params"
    sample_period: 0.1
    sample_field: "y_velocity"
  c: "osdt_example.models.sample_hold_sensor.C"
  f: "osdt_example.models.sample_hold_sensor.F"
  d: "osdt_example.models.sample_hold_sensor.D"
  g: "osdt_example.models.sample_hold_sensor.G"
  u: "osdt_example.models.sample_hold_sensor.U"
  y: "osdt_example.models.sample_hold_sensor.Y"
  id: "vel_sampler"


config:
  time: 9.0
  jumps: 300

env_load:
  path: "output/bb_sh"

env_save:
  path: "output/bb_sh"
  overwrite: True

figure1:
  pos_sensor: "pos_sampler"
  vel_sensor: "vel_sampler"


connections:
  matrix: [
    ["pos_sampler","ball","osdt_example.models.sample_hold_sensor.INPUT"],
    ["vel_sampler","ball","osdt_example.models.sample_hold_sensor.INPUT"],
    ["ball","pos_sampler","'test'"]
  ]
  get_systems: true
