data_file: null

controller:
  x:
    $class: "osdt_example.models.dubins_controller.State"
    turn: 1.0
    velocity: 0.5
  c: "osdt_example.models.dubins_controller.C"
  f: "osdt_example.models.dubins_controller.F"
  d: "osdt_example.models.dubins_controller.D"
  g: "osdt_example.models.dubins_controller.G"
  u: "osdt_example.models.dubins_controller.U_convert"
  y: "osdt_example.models.dubins_controller.Y"
  id: "dubins_controller"

vehicle:
  x:
    $class: "osdt_example.models.dubins_vehicle.State"
    x_position: 0.0
    y_position: 0.0
    orientation: 0.0
  c: "osdt_example.models.dubins_vehicle.C"
  f: "osdt_example.models.dubins_vehicle.F"
  d: "osdt_example.models.dubins_vehicle.D"
  g: "osdt_example.models.dubins_vehicle.G"
  u: "osdt_example.models.dubins_vehicle.U_convert"
  y: "osdt_example.models.dubins_vehicle.Y"
  id: "dubins_vehicle"


connections:
  matrix: [
    ["dubins_controller","dubins_vehicle","osdt_example.models.dubins_vehicle.VEHICLE"],
    ["dubins_vehicle","dubins_controller","osdt_example.models.dubins_vehicle.CONTROLLER"],
  ]
  get_systems: true

config:
  time: 9.0
  jumps: 300

main:
  actions: [
    ["osdt_example.models.dubins_controller.create", "data_file:controller"],
    [ "osdt_example.models.dubins_vehicle.create", "data_file:vehicle" ],
    ["osdt.connect_components","data_file:connections"],

    ["osdt.edit_config", "data_file:config"],
    ["osdt.run",{}],
    ["osdt_example.functions.dubins.octo_figure",{}],
    ["osdt.display",{}]
  ]