# get input value num_balls
ball_count: {~~: "osdt.to_int", value: "::num_balls"}
figure_title: "Random Bouncing Balls"

: {~~: "osdt.extras.loop", count: "::ball_count", function: "~~osdt.load_objfile", path: "randomized_bouncing_ball.yaml"}

: {~~: "osdt.set_integrator", integrator_type: "vode", max_step: 0.1}
: {~~: "osdt.set_configuration", max_plot_points: 1000}

: {~~: "osdt.run", time: 10.0, jumps: 20000}

fig: {~~: "osdt.create_figure", layout: [[1],[2]], width: 2000, height: 1000,  style: "increase_font_size.style"}

: {~~: "::fig::configure", subplot: 1, x_axis: "Time (s)", y_axis: "Position (m)", legend: false}
: {~~: "::fig::configure", subplot: 2, x_axis: "Time (s)", y_axis: "Velocity (m/s)", legend: false}

: {~~: "::fig::plot", subplot: 1, y: "y_position"}
: {~~: "::fig::plot", subplot: 2, y: "y_velocity"} 

#: {~~: "osdt.display"}
: {~~: "::fig::export", path: "files/bouncing_ball_random", format: "png", overwrite: false}