systems: {~~: "osdt.load_objfile", path: "::system_file", controller_id: "Controller (Sensor)", vehicle_id: "Vehicle (Sensor)"}
systems_unsampled: {~~: "osdt.load_objfile", path: "::system_file", controller_id: "Controller (Direct)", vehicle_id: "Vehicle (Direct)"}

vehicle_unsampled: "::systems_unsampled::vehicle"
controller_unsampled: "::systems_unsampled::controller"

: {~~: "::vehicle_unsampled::set", key: "~~osdt_example.models.dubins_vehicle.CONTROLLER", value: "::controller_unsampled"}
: {~~: "::controller_unsampled::set", key: "~~osdt_example.models.dubins_controller.VEHICLE", value: "::vehicle_unsampled"}

vehicle: "::systems::vehicle"
controller: "::systems::controller"

#sample_and_hold1: {~~: "osdt.load_objfile", path: "osdt_example/objfiles/sample_and_hold_system.yaml", sample_input: "::vehicle", sample_field: "x_position"}
#sample_and_hold2: {~~: "osdt.load_objfile", path: "osdt_example/objfiles/sample_and_hold_system.yaml", sample_input: "::vehicle", sample_field: "y_position"}
#sh1: "::sample_and_hold1::system"
#sh2: "::sample_and_hold2::system"

sample_and_hold_vehicle: {~~: "osdt.load_objfile", path: "osdt_example/objfiles/sample_and_hold_system_multi.yaml", sample_input: "::vehicle", sample_fields: ["x_position","y_position","orientation"], sampler_id: "Vehicle Sensor Value", sample_period: "::systems::sample_period"}
sample_and_hold_controller: {~~: "osdt.load_objfile", path: "osdt_example/objfiles/sample_and_hold_system_multi.yaml", sample_input: "::controller", sample_fields: ["turn","velocity"], sampler_id: "Controller Sensor Value", sample_period: "::systems::sample_period"}

sh_vehicle: "::sample_and_hold_vehicle::system"
sh_controller: "::sample_and_hold_controller::system"


: {~~: "::vehicle::set", key: "~~osdt_example.models.dubins_vehicle.CONTROLLER", value: "::sh_controller"}
: {~~: "::controller::set", key: "~~osdt_example.models.dubins_controller.VEHICLE", value: "::sh_vehicle"}


: {~~: "osdt.run", time: 40.0, jumps: 10000}



fig2: {~~: "osdt.create_figure", layout: [[1,1,4,4],[2,2,4,4],[3,3,4,4]], width: 2000, height: 1000, pad_h: 2.0, pad_w: 2.0, title: "::systems::figure_title",   style: "increase_font_size_dubins.style" }
: {~~: "::fig2::configure", subplot: 1, title: "X Position", x_axis: "Time (s)", y_axis: "Position (m)", legend: false}
: {~~: "::fig2::configure", subplot: 2, title: "Orientation",  x_axis: "Time (s)", y_axis: "Orientation (rad)", legend: false}
: {~~: "::fig2::configure", subplot: 3, title: "Turn State",  x_axis: "Time (s)", y_axis: "Turn State"}
: {~~: "::fig2::configure", subplot: 4, title: "X Position vs Y Position",  x_axis: "X Position (m)", y_axis: "Y Position (m)",color: [""]}

: {~~: "::fig2::plot", subplot: 1, y: "x_position"}
: {~~: "::fig2::plot", subplot: 2, y: "orientation"} 
: {~~: "::fig2::plot", subplot: 3, y: "turn", color: ["purple", "orange", "cyan"]}
#: {~~: "::fig2::plot", subplot: 3, y: "turn", color: "purple", system: "::sh_controller", label: ""}
#: {~~: "::fig2::plot", subplot: 3, y: "turn", color: "orange", system: "::controller", label: "Controller (Sampled)"}
#: {~~: "::fig2::plot", subplot: 3, y: "turn", color: "cyan", system: "::controller_unsampled", label: "Controller (Direct)"}

: {~~: "::fig2::plot", subplot: 4, x: "x_position", y: "y_position"}

: {~~: "::fig2::export", path: "files/dubins_sampled", format: "png",overwrite: false}
#fig1: {~~: "osdt.create_figure", layout: [[1]], width: 1200, height: 600, title: "Dubins Vehicle"}
#: {~~: "::fig1::plot", subplot: 1, y: "value",system: ["::sh_"]}


#: {~~: "osdt.display"}