args:
  system1: {~~: osdt_example.functions.simple_timer.generate_system_default, module_name: osdt_example.models.simple_timer, state: State, params: [Params]}





: {~~: osdt_example.functions.simple_timer.output_default_file, file_path: default_args, default_args: "::args"}




